[project]
name = "chatgpt-zulip-bot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "anyio>=4.14.2",
    "idna>=3.15",
    "openai>=2.16.0",
    "pygments>=2.20.0",
    "pytest>=9.0.3",
    "requests>=2.33.0",
    "tiktoken>=0.12.0",
    "urllib3>=2.7.0",
    "zulip>=0.9.1",
]
